import cx from "clsx";
import { ReactNode, useState } from "react";

import HandleIcon from "./icons/faqs/handle.svg";

let FAQ_BODY = `
Make a postive first impression in your listing's title, description, and amenities in Your Voice.
It's crucial because these elements directly influence a potential guest's decision to book. Craft
a bio that resonates personally with guests. This can create a sense of comfort and security,
encouraging bookings. Understand what guests have enjoyed and what areas need improvement, hosts can
make informed decisions to enhance their property and service`;

function FaqEntry({ title, body }: { title: ReactNode; body: ReactNode }) {
  let [open, setOpen] = useState(false);

  return (
    <div
      onClick={() => setOpen(x => !x)}
      className={cx(
        "border-b-2 border-dotted border-[#9FB4C4] py-7 last:border-0"
      )}
    >
      <div className='mx-auto grid max-w-[1090px] cursor-pointer grid-cols-[auto,1fr] px-6'>
        <img
          src={HandleIcon}
          className={cx(
            "mr-6 w-[50px] shrink-0 transition-transform sm:mr-8 sm:w-[80px] md:mr-12 lg:mr-16",
            open && "rotate-90"
          )}
        />
        <h2 className='max-w-4xl select-none text-2xl self-center font-semibold leading-8 sm:text-3xl sm:leading-10'>
          {title}
        </h2>
        {open && (
          <p className='col-[1/-1] row-[2/3] max-w-4xl pt-4 text-lg font-normal leading-normal sm:col-[2/3]'>
            {body}
          </p>
        )}
      </div>
    </div>
  );
}

export function Faqs() {
  return (
    <section id='faqs' className='bg-white py-24'>
      <div className='mx-auto max-w-[1090px] px-6'>
        <h1 className='text-6xl leading-[4rem] sm:max-w-xl'>FAQ</h1>
      </div>

      <div className='mt-16'>
        <FaqEntry
          title={"What is AutoBlogger?"}
          body={
            "AutoBlogger is an AI-powered content generation tool designed to simplify the process of creating blog posts. By leveraging advanced algorithms, AutoBlogger automatically generates high-quality articles based on your specified keyword and preferences."
          }
        />
        <FaqEntry
          title={"How does AutoBlogger work?"}
          body={
            "AutoBlogger works by analyzing your provided keyword and generating relevant content based on it. You can customize your options, such as generating post tags and excerpts, and specify the number of sections and articles you need. Once you've input your preferences, AutoBlogger swiftly generates polished blog posts ready for publication."
          }
        />
        <FaqEntry
          title={"What types of topics can AutoBlogger generate content for?"}
          body={
            "AutoBlogger can generate content for a wide range of topics spanning various industries and interests. Whether you're blogging about travel, technology, health, finance, or any other niche, AutoBlogger can tailor articles to suit your needs."
          }
        />
        <FaqEntry
          title={"Can I customize the generated content?"}
          body={
            "While AutoBlogger generates content automatically, you can customize certain aspects of the articles, such as enabling post tags and excerpts. Additionally, you have the option to specify the number of sections and articles you require, giving you control over the final output."
          }
        />
        <FaqEntry
          title={"Is AutoBlogger suitable for beginners?"}
          body={
            "Yes, AutoBlogger is user-friendly and suitable for bloggers of all levels, including beginners. Our intuitive interface makes it easy to input your keyword, customize your options, and generate content with just a few clicks."
          }
        />
        <FaqEntry
          title={"Can I download the articles generated by AutoBlogger?"}
          body={
            "Yes, once your articles are generated, you can download them effortlessly. Simply access the generated content and download it in your preferred format for easy sharing on your blog or website."
          }
        />
        <FaqEntry
          title={"How does AutoBlogger integrate with Wordpress?"}
          body={
            "AutoBlogger seamlessly integrates with Wordpress, allowing you to upload your generated articles directly to your Wordpress site. To enable this feature, you'll need to provide your Wordpress credentials, including your Rest API URL, username, and password."
          }
        />
      </div>
    </section>
  );
}
